fos_elastica:
    clients:
        default: { host: %elastic_host%, port: %elastic_port% }
    indexes:
        obtao_blog:
            client: default
            types:
                article:
                    mappings:
                        id:
                            type: integer
                        title :
                            type : string
                        author :
                            type : string
                        release_year :
                            type : date
                        publisher :
                            type : string
                        genre :
                            type : string
                        language :
                            type : string
                        pages_number :
                            type : integer
                        description :
                            type : string
                        rating :
                            type : integer
                        date_created :
                            type : datetime
                        book_name :
                            type : string
                        ISBN :
                            type : string
                        title : ~
                        content : ~
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Book
                        finder: ~
                        provider: ~
                        listener: ~