<?php

/**
 * Created by PhpStorm.
 * User: Robertas
 * Date: 10/16/2017
 * Time: 10:26 PM
 */
namespace AppBundle\Filter;

use AppBundle\Form\Type\BookType;
use Doctrine\DBAL\Types\DateType;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Routing\Router;
class BookFilter extends BookType
{
    var $filterArray = [
        'title',
        'author',
        'translate_year',
        'release_year',
        'language',
        'page_number',
        'rating',
        'price',
        'times_downloaded',
        'comments_added',
    ];

    var $filterFiedlsForQuery = [
        'title' => 'b.title',
        'author' => 'b.author',
        'translate_year' => 'b.translate_year',
        'release_year' => 'b.release_year',
        'language' => 'b.language',
        'page_number' => 'b.page_number',
        'rating' => 'b.rating',
        'price' => 'b.price',
        'times_downloaded' => 'b.times_downloaded',
        'comments_added' => 'b.comments_added',
    ];

    var $filterAdditionalOptions = array();

    public function __construct(EntityManager $em, Router $router)
    {
        $this->em = $em;
        $this->router = $router;
    }

    public function buildForm(\Symfony\Component\Form\FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $builder->add('title', TextType::class);

        $builder->add('author', TextType::class);

        $builder->add('translate_year', DateType::class);

        $builder->add('release_year', DateType::class);

        $builder->add('language', TextType::class);

        $builder->add('page_number', NumberType::class);

        $builder->add('rating', NumberType::class);

        $builder->add('price', MoneyType::class);

        $builder->add('times_downloaded', NumberType::class);

        $builder->add('comments_added', NumberType::class);
    }

    public function getName()
    {
        return 'book_filter';
    }

    public function configureOptions(\Symfony\Component\OptionsResolver\OptionsResolver $resolver)
    {
        parent::configureOptions($resolver);

        $resolver->setDefault('data_class', null);
    }

}