security:
    encoders:
        web\Entity\User: bcrypt
    firewalls:
            main:
                anonymous: ~
                form_login:
                    login_path: login
                    check_path: login
access_control:
    - { path: ^/, roles: ROLE_ADMIN }
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: ROLE_ADMIN }