AppBundle\Entity\Book:
    type: entity
    repositoryClass: AppBundle\Entity\BookRepository
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        title:
            type: string
            length: 255
        author:
            type: string
            length: 255
        release_year:
            type: date
            nullable: true
        publisher:
            type: string
            length: 255
        genre:
            type: string
            length: 255
        language:
            type: string
            length: 255
        pages_number:
            type: integer
        description:
            type: string
            nullable: true
            length: 510
        comments_count:
            type: integer
            nullable: true
        rating:
            type: integer
            nullable: true
        readers_count:
            type: integer
            nullable: true
        last_read_page:
            type: integer
            nullable: true
    lifecycleCallbacks: {  }
