AppBundle\Entity\Note:
    type: entity
    repositoryClass: AppBundle\Entity\NoteRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        username:
            type: string
            lenght: 255
        note:
            type: string
            lenght: 510
        created:
            type: datetime
            nullable: true
        user_email:
            type: string
            nullable: true
    lifecycleCallbacks: {  }
#    manyToOne:
#        book:
#            targetEntity: AppBundle\Entity\Book
#            inversedBy: note
#            joinColumn:
#                name: book_id
#                referencedColumnName: id