<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends EntityRepository
{
    public function getValuesList()
    {
        $qb = $this->createQueryBuilder('m');

        $qb->select('m.file_name')
//            ->join('m.user', 'u')
//            ->where($qb->expr()->in('m.id', $ids))
            ->orderBy('m.id');

        $items = $qb->getQuery()->getArrayResult();
        $lines = [];

//        $fileNames = $this->_em->getRepository('AppBundle:Media')->findBy(['file_name' => $ids]);

        /* @var $item Media */
//        foreach ($items as $item) {
//            $lines[$item->getFileName()] = $item;
//        }

        return $items;
    }

    public function getLast()
    {
        return $this->createQueryBuilder('m')->
        select('m.file_name')->
        orderBy('m.date_created', 'DESC')->
        setMaxResults(1)->
        getQuery()->
        getOneOrNullResult();
    }

    public function openFile($fileName)
    {
        $qb = $this->createQueryBuilder('m');

        $qb->select('m.file_name')
            ->setParameter('file_name', $fileName);

        $item = $qb->getQuery()->getOneOrNullResult();

        return $item;
    }
}
