<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends EntityRepository
{
    public function getValuesList($noteId)
    {
        $qb = $this->createQueryBuilder('n');

        $qb->select('b')
            ->join('n.book', 'b')
            ->where('b.id =:id')
            ->setParameter('id', $noteId);

        $items = $qb->getQuery()->getArrayResult();

        return $items;
    }

    public function findAllQueryBuilder($filter = '')
    {
        $qb = $this->createQueryBuilder('note');

        if ($filter) {
            $qb->andWhere('note.username LIKE :filter OR note.note LIKE :filter OR note.created LIKE :filter')
                ->setParameter('filter', '%'.$filter.'%');
        }

        return $qb->getQuery()->getResult();
    }
}
