<?php

namespace AppBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function userRole($id, $role)
    {
        $qb = $this->createQueryBuilder('u');

        $qb->select('u')
            ->where('u.id = :user')
            ->andWhere('u.role LIKE :roles')
            ->setParameter('user', $id)
            ->setParameter('roles', '%"'. $role . '"%');

        $user = $qb->getQuery()->getResult();

        if(count($user) >= 1) {
            return true;
        } else {
            return false;
        }
    }

    public function getRole()
    {
        $qb = $this->createQueryBuilder('u');

        $qb->select('u.role')
            ->where('u.role' == "ROLE_ADMIN");

        $user = $qb->getQuery()->getResult();

//        if($user == "ROLE_ADMIN") {
//            return true;
//        } else {
//            return false;
//        }
        return $user;
    }

    public function listExceptAdmin()
    {
        $qb = $this->createQueryBuilder('u');

        $qb->select('u')
            ->where('u.id != 2');

        $items = $qb->getQuery()->getResult();

        return $items;
//        $qb->createQuery("SELECT c FROM Category c WHERE c.id != 0")->getResult();
    }
}
